server:
  port: 8081
spring:
  application:
    name: Covidtest
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/testnat?useSSL=false&serverTimezone=UTC
    username: root
    password: 264979
  redis:
    host: 192.168.141.128
    port: 6379
    password: 264979
    timeout: 3000  #连接超时时间 单位毫秒
    lettuce:
      pool:
        max-active: 10   #连接池最大可以被分配成jedis或者lettuce实例的个数
        max-idle: 10    #最大空闲连接
        min-idle: 1    #最小空闲连接
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略空值
mybatis-plus:
  type-aliases-package: com.Covidtest.entity # 别名扫描包
